Module2 task1
htmlacademy-adaptive/198989-mishka-27 pull request #2
Opened 2022-12-02 13:49 UTC by Bwomsamdi

Домашнее задание раздела №2.

2022-12-03 15:33 UTC, nikopol-fw requested changes

2022-12-03 15:33 UTC, nikopol-fw commented on Readme.md
> +* Наставник: [Николай Думчев](https://https://htmlacademy.ru/profile/nikopol-fw).
`https://https://` ? ;)

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +      <nav class="navigation">
Нет никакого смысла в nav заталкивать вообще все, что есть в шапке. С таким же успехом, можно было бы nav не добавлять. Все-таки семантические теги нужны, чтобы отделить одну информацию от другой.
Посмотри в сторону, чтобы выделить в nav только список ссылок, ведущих на статические разделы сайта.

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          <svg class="logo logo--mobile" aria-hidden="true" focusable="false" width="102" height="34" fill="currentColor" viewBox="0 0 102 34" xmlns="http://www.w3.org/2000/svg">
Давай svg заменим на тег img?
Не вижу интерактивных изменений, которые помещают нам управлять оформлением при клике или наведении, то есть управлять внутренностями svg нам не придется.

Какие плюсы от этой замены?
1. Уменьшим код в разметке. Просто удобнее.
2. Картинка будет отдельным запросом приходить и кешироваться.

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          </li>
Давай "Новые поступления" и "Распродажа" сделаем подсписком "Каталога товаров". По смыслу очень похоже, что это подкатегории именно каталога

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +            </blockquote>
Думаю, что blockquote нужно убрать. Да, у нас прямая речь как бы. Но по факту мы не цитируем. Мы не можем сослаться на источник, указать ссылку. Нет смысла использовать здесь этот тег.

Заложи здесь лучше список, хоть комментарий и один. Подразумевается, что их должно быть много

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          <h2 class="visually-hidden">Логитип компании и ссылка на главную страницу.</h2>
Явный перебор с секциями и заголовок оч. странный.
Действительно ли одна ссылка заслуживает отдельный секции?

Также, давай также как в шапке svg => img ?

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          <ul class="social__list">
Просто список, без секции. Излишнее предание списку веса. Не мельчи с секциями ;)

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          </a>
Давай и img и текст обернем в ссылку? Будет удобнее для клика по элементу

2022-12-03 15:33 UTC, nikopol-fw commented on source/index.html
> +          <fieldset class="modal__group">
fieldset без form смысла не имеет. Как и input'ы.
Как минимум нужно добавить тег формы. А далее как следствие превратить ссылку "Добавить" в кнопку submit

2022-12-03 15:33 UTC, nikopol-fw commented on source/catalog.html
> +      </section>
Неее :) Так не бывает))
h1 — заголовок страницы. Он не должен быть внутри секции.
Зачем тут вообще секция для заголовка? Тебя путает оформление

2022-12-03 15:33 UTC, nikopol-fw commented on source/catalog.html
> +            <a class="catalog__item-link" href="#">
Посмотри в ТЗ, что должно являться ссылкой. Там есть

2022-12-03 15:33 UTC, nikopol-fw commented on source/catalog.html
> +              <h2 class="catalog__item-title">Зайчик-попрыгайчик</h2>
h3, потому что h2 потенциально — это заголовок секции. Даже если мы его явно не обозначаем, при добавлении заголовков мы учитываем именно уровень вложенности, уровень деления информации.
h1 — страница
h2 — крупные блоки на странице
h3 — элементы внутри блоков, или подблоки
h4 — дальнейшее выделение чего-то внутри подблоков
и т.д.

2022-12-03 15:33 UTC, nikopol-fw commented on source/catalog.html
> +      </section>
Нужно добавить кнопку "Воспроизвести" (play, белый треугольник на зеленом фоне посередине постера), которую потом стилизуем, чтобы в теории ее можно было использовать в шаблоне сайта. Иначе программисты не смогут ее нигде взять

2022-12-03 22:40 UTC, Bwomsamdi commented on Readme.md
> +* Наставник: [Николай Думчев](https://https://htmlacademy.ru/profile/nikopol-fw).
=( 
Fixed

2022-12-03 22:44 UTC, Bwomsamdi commented on source/index.html
> +          </a>
Fixed.

2022-12-03 22:55 UTC, Bwomsamdi commented on source/index.html
> +            </blockquote>
Fixed.

2022-12-04 13:49 UTC, Bwomsamdi commented on source/index.html
> +          <svg class="logo logo--mobile" aria-hidden="true" focusable="false" width="102" height="34" fill="currentColor" viewBox="0 0 102 34" xmlns="http://www.w3.org/2000/svg">
Fixed.

2022-12-04 13:55 UTC, Bwomsamdi commented on source/index.html
> +          </li>
Fixed.

2022-12-04 13:55 UTC, Bwomsamdi commented on source/index.html
> +      <nav class="navigation">
Fixed.

2022-12-04 14:04 UTC, Bwomsamdi commented on source/index.html
> +          <fieldset class="modal__group">
Fixed.

2022-12-04 14:07 UTC, Bwomsamdi commented on source/catalog.html
> +      </section>
Fixed.

2022-12-04 14:20 UTC, Bwomsamdi commented on source/catalog.html
> +            <a class="catalog__item-link" href="#">
Fixed.

2022-12-04 14:23 UTC, Bwomsamdi commented on source/catalog.html
> +              <h2 class="catalog__item-title">Зайчик-попрыгайчик</h2>
Fixed.

2022-12-04 14:39 UTC, Bwomsamdi commented on source/index.html
> +          <ul class="social__list">
Заменила на дивы и переделала классы.

2022-12-04 14:40 UTC, Bwomsamdi commented on source/index.html
> +          <h2 class="visually-hidden">Логитип компании и ссылка на главную страницу.</h2>
Fixed.

2022-12-04 14:56 UTC, Bwomsamdi commented on source/catalog.html
> +      </section>
Fixed.

2022-12-06 19:03 UTC, nikopol-fw approved these changes

2022-12-06 19:06 UTC, merged