Добавляет базовую стилизацию
htmlacademy-adaptive/198989-mishka-27 pull request #3
Opened 2022-12-10 13:45 UTC by Bwomsamdi

Домашнее задание по разделу №3.

2022-12-10 16:51 UTC, nikopol-fw requested changes

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/style.less
> +  font-style: normal;
Точно лишние, ничего не меняют

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/site-list.less
> +}
Думаю, что стоит прятать сам список, а не его пункты

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/user-list.less
> +}
А по факту стили получились одинаковые. Может лучше search и cart объединим в единый класс. Отличия потом сделаешь через модификаторы. А может их вообще не будет, а будет svg внутри. Которое уже есть, кстати

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/products.less
> +}
Стили одинаковые, классы разные. То же самое. Зачем?

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/promo.less
> +  .normalize-title();
`padding: 0;` в данном случае не нужен

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/promo.less
> +}
Выставь общий `line-height: 20px;` для родительского элемента `promo__item`. Высота строки будет наследоваться

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/button.less
> +}
Выставь кнопке дополнительные не очень большие отступы справа и слева, чтобы текст точно не мог прилипнуть к краям. Но маленькие, чтобы было легче встраивать кнопки разных размеров без переопределения

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/button.less
> +}
Давай модификаторы писать внутри элемента через &? Так код становится нагляднее, все что касается одного элемента лежит визуально в одном месте. Поддерживать такой код проще
```less
.button {
    &--secondary {
        ...
    }
}
```

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/reviews.less
> +}
У нас используется тег <cite>. Мы убрали цитату и тег неуместен. Давай заменим, пусть даже на <p>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/copyright.less
> +  line-height: 18px;
Не обязательно на самом деле не для больших текстов передавать line-height по макету 1 в 1. Рекомендую выставить `line-height: 1`, потом проще будет в сетке с этим работать

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/visually-hidden.less
> +}
Можно в global завести файл common (или scaffolding, utils, др.), в который складывать служебные классы

2022-12-10 16:51 UTC, nikopol-fw commented on source/form.html
> +        </div>
Вынеси из формы, сделай h1, на самом деле это блок один в один как в каталоге

2022-12-10 16:51 UTC, nikopol-fw commented on source/form.html
>        <h1 class="visually-hidden">Форма отправки заказа.</h1>
Никто не будет в поисковике искать "Форма отправки заказа". То что ниже "Вязание на заказ" — самый настоящий заголовок страницы. Не усложняй

2022-12-10 16:51 UTC, nikopol-fw commented on source/form.html
>            <h2 class="visually-hidden">Выберите тип изделия.</h2>
Это заголовок чего? Да и вообще это призыв к действию, а не заголовок. Думаю стоит просто удалить

2022-12-10 16:51 UTC, nikopol-fw commented on source/form.html
> +            <h3 class="main-container__form-title">ТИП</h3>
Должен быть внутри fielset. Возможно стоит заменить на legend, но не уверен, что не будет проблем с его стилизацией. Ниже проделать тоже самое.

Не пиши заглавными буквами контент, если в этом нет смысла с точки зрения информации. На дизайнера в этом плане надеятбся не стоит. Аббревиатуры — да. Это же просто стилизуется на css

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/control.less
> +}
span удалить, стили перенести для label. Лишняя обертка

2022-12-10 16:51 UTC, nikopol-fw commented on source/less/blocks/info.less
> +}
Давай мы попробуем все fieldset'ы обозначить одним классом. Они все похожи, просто внутри разные input'ы. Если где-то в макете огрехи — добавим модификаторы

2022-12-12 13:40 UTC, Bwomsamdi commented on source/less/style.less
> +  font-style: normal;
Fixed.

2022-12-12 13:44 UTC, Bwomsamdi commented on source/less/blocks/site-list.less
> +}
Fixed.

2022-12-12 13:46 UTC, Bwomsamdi commented on source/less/blocks/user-list.less
> +}
Fixed.

2022-12-12 13:52 UTC, Bwomsamdi commented on source/less/blocks/products.less
> +}
Здесь разные цвета фона, сделала один стиль и ко второму добавила модификатор.

2022-12-12 13:56 UTC, Bwomsamdi commented on source/less/blocks/promo.less
> +  .normalize-title();
Fixed.

2022-12-12 13:57 UTC, Bwomsamdi commented on source/less/blocks/promo.less
> +}
Fixed.

2022-12-12 14:00 UTC, Bwomsamdi commented on source/less/blocks/button.less
> +}
По 2px достаточно?

2022-12-12 14:08 UTC, Bwomsamdi commented on source/less/blocks/button.less
> +}
Fixed.

2022-12-12 14:12 UTC, Bwomsamdi commented on source/less/blocks/reviews.less
> +}
Заменила span на cite.

2022-12-12 14:14 UTC, Bwomsamdi commented on source/less/blocks/copyright.less
> +  line-height: 18px;
Fixed.

2022-12-12 14:16 UTC, Bwomsamdi commented on source/less/blocks/visually-hidden.less
> +}
Выбрала common.

2022-12-12 14:20 UTC, Bwomsamdi commented on source/form.html
> +        </div>
Fixed.

2022-12-12 14:21 UTC, Bwomsamdi commented on source/form.html
>        <h1 class="visually-hidden">Форма отправки заказа.</h1>
Удалила, когда правила другое. Запуталась в заголовках( должно было получиться как в каталоге(

2022-12-12 15:37 UTC, Bwomsamdi commented on source/form.html
>            <h2 class="visually-hidden">Выберите тип изделия.</h2>
Fixed.

2022-12-12 15:37 UTC, Bwomsamdi commented on source/form.html
> +            <h3 class="main-container__form-title">ТИП</h3>
Fixed.

2022-12-12 15:40 UTC, Bwomsamdi commented on source/less/blocks/control.less
> +}
Fixed.

2022-12-12 15:47 UTC, Bwomsamdi commented on source/less/blocks/info.less
> +}
Создала отдельный блок field для всех полей с вводом информации.

2022-12-13 03:02 UTC, nikopol-fw commented on source/less/blocks/reviews.less
> +}
Упущена часть текста в комментарии. Написал подробнее в чате

2022-12-13 03:08 UTC, nikopol-fw approved these changes

2022-12-13 03:08 UTC, merged