Module4 task1
htmlacademy-adaptive/198989-mishka-27 pull request #4
Opened 2022-12-23 15:02 UTC by Bwomsamdi

Домашнее задание по разделу №4.

2022-12-25 08:01 UTC, nikopol-fw requested changes

2022-12-25 08:01 UTC, nikopol-fw commented on source/less/global/variable.less
> +@desktop-width: 1200px;
В критерии указано, что десктопная версия в Мишке начинается с 1150px
https://up.htmlacademy.ru/adaptive/27/criteries#b11

2022-12-25 08:01 UTC, nikopol-fw commented on source/less/blocks/main-container.less
> +}
Чтобы получилось хорошо, следует создать служебный класс `container` и в него перенести настройку контентной области + отступы боковые от краев экрана.
И далее вместо того, чтобы весь main ограничиваться по ширине, добавлять div'ы внутри блоков, где нужно ограничение по контентной ширине. Либо добавлять класс container к уже существующим тегам, если складно будет и без конфликтов.

Этот служебный класс не должен в себя включать ничего лишнего. Иначе его будет сложно применять во многих местах

2022-12-25 08:10 UTC, nikopol-fw commented on source/index.html
> +      <p class="main-container__remark main-container__remark--inner">Бесплатная доставка по России</p>
Этот элемент должен быть в шапке, как и было. Он повторяется от страницы к странице

2022-12-26 14:13 UTC, Bwomsamdi commented on source/less/global/variable.less
> +@desktop-width: 1200px;
Fixed.

2022-12-26 14:29 UTC, Bwomsamdi commented on source/index.html
> +      <p class="main-container__remark main-container__remark--inner">Бесплатная доставка по России</p>
Fixed.

2022-12-26 21:55 UTC, Bwomsamdi commented on source/less/blocks/main-container.less
> +}
Fixed.

2022-12-28 10:12 UTC, nikopol-fw approved these changes

2022-12-28 10:12 UTC, merged