Module6 task1
htmlacademy-adaptive/198989-mishka-27 pull request #6
Opened 2023-01-04 21:23 UTC by Bwomsamdi

Домашнее задание раздела №6.

2023-01-07 22:27 UTC, nikopol-fw requested changes

2023-01-07 22:27 UTC, nikopol-fw commented on source/form.html
>                <svg class="main-footer__link-logo logo" aria-hidden="true" focusable="false" width="86" height="28" fill="currentColor" viewBox="0 0 102 34" xmlns="http://www.w3.org/2000/svg">
logo надо переделать. Ты хитро реализовала изменение цвета и дополнительных элементов. Но все-таки логотип это вся картинка целиком, и распознаваться должна именно так, а не составляться из каких-то стилей.

Можно скомбинировать 3-и svg инлайновых, которые отображаются в зависимости от media. Можно пойти через picture и встроить как адаптивную графику

2023-01-07 22:27 UTC, nikopol-fw commented on source/less/blocks/index/products.less
> +    background-image: url("../img/hero@2x.jpg");
Нужно указать правила для размеров фонового изображения. Сейчас картинка x2 отображается не по макету.
Чаще всего о размере изображений всегда следует думать и указывать точные правила в css, не доверяя размерам фактического изображения. Либо если картинка статичная, определяется верстальщиком, строго указывать размеры
![image](https://user-images.githubusercontent.com/22588831/211172293-e8b632e6-19dc-4225-ba44-2ac559afa181.png)

2023-01-07 22:27 UTC, nikopol-fw commented on source/index.html
> +              <img class="promo__image" src="img/catalog/triple-set.jpg" srcset="img/triple-set@2x.jpg 2x" width="260" height="315" alt="Вязанные корзинки ручной работы разных цветов.">
Не загружается картинка. Кажется ошибка в пути
![image](https://user-images.githubusercontent.com/22588831/211172417-f4ef7fb0-a9e1-4ac6-b645-8d1ca330be84.png)

2023-01-08 00:10 UTC, Bwomsamdi commented on source/index.html
> +              <img class="promo__image" src="img/catalog/triple-set.jpg" srcset="img/triple-set@2x.jpg 2x" width="260" height="315" alt="Вязанные корзинки ручной работы разных цветов.">
Fixed.

2023-01-08 00:36 UTC, Bwomsamdi commented on source/less/blocks/index/products.less
> +    background-image: url("../img/hero@2x.jpg");
Fixed.

2023-01-08 01:18 UTC, Bwomsamdi commented on source/form.html
>                <svg class="main-footer__link-logo logo" aria-hidden="true" focusable="false" width="86" height="28" fill="currentColor" viewBox="0 0 102 34" xmlns="http://www.w3.org/2000/svg">
Fixed.

2023-01-08 16:17 UTC, nikopol-fw approved these changes

2023-01-08 16:17 UTC, merged